site_name: Spry Language
site_url: http://sprylang.org
site_dir: www
copyright: "Spry is licensed under the <a href='https://github.com/gokr/spry/blob/master/LICENSE'>MIT license"
repo_name: GitHub
repo_url: http://github.com/gokr/spry
site_description: The Spry Programming language homepage
site_author: GÃ¶ran Krampe
site_favicon: favicon.ico
use_directory_urls: false
markdown_extensions:
    - toc:
        permalink: " #"
    - admonition:
pages:
- Home: index.md
- Language Manual: manual.md
- Articles:
    - Getting Started: start.md
    - Spry vs Smalltalk: spry-vs-smalltalk.md 
- Community: community.md
- REPL: repl.md

- About: about.md
theme: cinder
extra_css:
    - css/highlight-fix.css
    - css/darkula.css
